steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/mongodb-loader', './mongodb_loader']
  #   id: 'Build MongoDB Loader Image'

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/mongodb-loader']
  #   id: 'Push MongoDB Loader Image'

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'gcr.io/$PROJECT_ID/mysql-loader', './mysql_loader']
  #   id: 'Build MySQL Loader Image'

  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'gcr.io/$PROJECT_ID/mysql-loader']
  #   id: 'Push MySQL Loader Image'
  # #  sGKE
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'mongodb-deployment.yaml']
  #   id: 'Deploy MongoDB'
  #   env:
  #   - 'CLOUDSDK_COMPUTE_ZONE=your-zone'
  #   - 'CLOUDSDK_CONTAINER_CLUSTER=your-cluster'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'mysql-deployment.yaml']
  #   id: 'Deploy MySQL'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'metabase-deployment.yaml']
  #   id: 'Deploy Metabase'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'etl-app-deployment.yaml']
  #   id: 'Deploy ETL App'

  # - name: 'gcr.io/cloud-builders/kubectl'
  #   args: ['apply', '-f', 'init-mongodb-data-fetcher-deployment.yaml']
  #   id: 'Deploy MongoDB Data Fetcher'

  # # Build the Docker image
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['build', '-t', 'LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE:TAG', '.']

  # # Push the image to Artifact Registry
  # - name: 'gcr.io/cloud-builders/docker'
  #   args: ['push', 'LOCATION-docker.pkg.dev/PROJECT-ID/REPOSITORY/IMAGE:TAG']

  # # Set up kubectl
  # - name: 'gcr.io/cloud-builders/kubectl'
  #   entrypoint: 'bash'
  #   args:
  #     - '-c'
  #     - |
  #       gcloud container clusters get-credentials kubecluster --zone us-central1 --project container-412111
  #       kubectl set image deployment/mysql-deployment.yaml CONTAINER_NAME=mysql-deployment

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'container-412111', '--zone', 'us-central1', '--project', '$PROJECT_ID']
    id: 'Setup GKE Credentials'

  # Деплой сервисов в GKE
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'etl-app-deployment.yaml']
    id: 'Deploy ETL App'