apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: etl-app
  name: etl-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: etl-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/t3w3-project2-building-microservices-deploy-to-kubernetes-app-network: "true"
        io.kompose.service: etl-app
    spec:
      containers:
        - args:
            - python
            - /app/mysql_loader/datatransfer_mongodb_mysql.py
          image: etl-app
          name: etl-container
          volumeMounts:
            - mountPath: /app/mysql_loader
              name: etl-app-claim0
      restartPolicy: Always
      volumes:
        - name: etl-app-claim0
          persistentVolumeClaim:
            claimName: etl-app-claim0
