apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: init-mongodb-data-fetcher-claim0
  name: init-mongodb-data-fetcher-claim0
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
