apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: init-mongodb-data-fetcher
  name: init-mongodb-data-fetcher
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init-mongodb-data-fetcher
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/t3w3-project2-building-microservices-deploy-to-kubernetes-app-network: "true"
        io.kompose.service: init-mongodb-data-fetcher
    spec:
      containers:
        - image: init-mongodb-data-fetcher
          name: data-fetcher
          volumeMounts:
            - mountPath: /app/mongodb_loader
              name: init-mongodb-data-fetcher-claim0
      restartPolicy: Always
      volumes:
        - name: init-mongodb-data-fetcher-claim0
          persistentVolumeClaim:
            claimName: init-mongodb-data-fetcher-claim0
