apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: metabase
  name: metabase
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: metabase
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (HEAD)
      labels:
        io.kompose.network/t3w3-project2-building-microservices-deploy-to-kubernetes-app-network: "true"
        io.kompose.service: metabase
    spec:
      containers:
        - env:
            - name: MB_DB_DBNAME
              value: hogwarts
            - name: MB_DB_FILE
              value: /metabase-data/metabase.db
            - name: MB_DB_HOST
              value: mysql-container
            - name: MB_DB_PASS
              value: admin
            - name: MB_DB_PORT
              value: "3306"
            - name: MB_DB_TYPE
              value: mysql
            - name: MB_DB_USER
              value: admin
            - name: MB_DB_USE_SSL
              value: "false"
          image: metabase/metabase
          name: metabase-container
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /metabase-data
              name: metabase-data
      restartPolicy: Always
      volumes:
        - name: metabase-data
          persistentVolumeClaim:
            claimName: metabase-data
