FROM python:3.8-slim

WORKDIR /app
COPY requirements.txt /app/
RUN ls -la /app/
RUN pip install -r requirements.txt
COPY datafetch_load_mongodb.py /app/


CMD ["python", "/app/mongodb_loader/datafetch_load_mongodb.py"]
#CMD tail -f /dev/null